name: Dart CI

on: [push]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Analyze platform interface
        run: cd webauthn_secure_storage_platform_interface && flutter pub get && flutter analyze
      - name: Analyze app-facing package
        run: cd webauthn_secure_storage && flutter pub get && flutter analyze
      - name: Analyze web package
        run: cd webauthn_secure_storage_web && flutter pub get && flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Test platform interface
        run: cd webauthn_secure_storage_platform_interface && flutter pub get && flutter test
      - name: Test app-facing package
        run: cd webauthn_secure_storage && flutter pub get && flutter test
      - name: Test web package
        run: cd webauthn_secure_storage_web && flutter pub get && flutter test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        buildcommand: [linux]
        os: [ubuntu-22.04]
        exclude:
          - os: ubuntu-22.04
            buildcommand: linux
        include:
#          No macos build for now, have to configure code signing..
#          - buildcommand: macos
#            os: macos-latest
          - buildcommand: ios
            buildargs: --no-codesign
            os: macos-latest
          - buildcommand: windows
            os: windows-latest
          - buildcommand: linux
            os: ubuntu-latest
          - buildcommand: appbundle
            os: ubuntu-latest
          - buildcommand: web
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: actions/setup-java@v4
        if: matrix.buildcommand == 'appbundle'
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Patch for linux build
        if: matrix.buildcommand == 'linux'
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libsecret-1-dev
          flutter doctor
      - name: Enable build
        if: matrix.buildcommand == 'macos' || matrix.buildcommand == 'linux'
        run: flutter config --enable-${{ matrix.buildcommand }}-desktop
      - name: Build for ${{ matrix.buildcommand }}
        run: cd webauthn_secure_storage/example && flutter build ${{ matrix.buildcommand }} ${{ matrix.buildargs }}
